version: "3"
services:
  eleventy:
    image: node:16-slim
    volumes:
      - ${PWD}/src:/app
    working_dir: /app
    environment:
      - DEBUG=Eleventy*
    command: ["npx", "-p", "@11ty/eleventy", "eleventy", "--watch", "--serve"]
    ports:
      - 8080:8080
