version: "3"
services:
  altaf-eleventy:
    image: node:16-slim
    volumes:
      - ${PWD}/src:/app
    working_dir: /app
    command: ["npx", "-p", "@11ty/eleventy", "eleventy", "--watch", "--serve"]
    ports:
      - 8080:8080
  # eleventy:
  #   build: .
  #   volumes:
  #     - ./src:/src/
  #   working_dir: /src
  #   ports:
  #     - "8000:8080"  
  # pg:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_db=bballstats
  #   ports:
  #     - '5432:5432'
  #   volumes: 
  #     - ./postgres-data:/var/lib/postgresql/data
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"