version: "3"
services:
  eleventy:
    image: node:16-slim
    volumes:
      - ${PWD}/src:/app
      - ${PWD}/docs:/app/_site
    working_dir: /app
    # environment:
    #   - DEBUG=Eleventy*
    # command: ["npx", "-p", "@11ty/eleventy", "eleventy", "--watch", "--serve"]
    command: /bin/bash -c "npm install && npx eleventy --watch --serve"
    ports:
      - 8080:8080
